### ISSUE TITLE
gcloud?

### ISSUE THREAD

**Issue by stephenplusplus** [sramam/gcloud-promise#1]
Hello, just stopping by to say a) nice library! and b) there's an official Node.js client library that might make accessing the cloud services easier: https://github.com/googlecloudplatform/gcloud-node -- thought you might be able to integrate it here to save you some trouble.

**Comment by sramam** [comment]
Thanks stephenplusplus!
I did look very closely at gcloud-node.

This is an attempt to provide a gcloud interface based on promises.
IMHO, it yields simpler code - both in the library and application,  but it is still early days. 

Please do let me know if you decide to try it out and have ideas on how to improve it.

**Comment by stephenplusplus** [comment]
Thanks @sramam :)
